<?php
/**
 * Pixel Redirect
 *
 * @package ShortLinksPro_Advanced_Redirects
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Add the "Pixel" redirect type to the interface dropdown.
 *
 * @since 1.0.0
 *
 * @param array $types Redirect types registered by ShortLinksPro.
 * @return array Modified redirect types array.
 */
add_filter( 'shortlinkspro_redirect_types', 'slp_advanced_add_pixel_redirect_type' );
function slp_advanced_add_pixel_redirect_type( $types ) {
    $types['pixel'] = 'Pixel 1x1 (Transparente)';
    return $types;
}

/**
 * Prevent the core from aborting when the redirect URL is empty for pixel links.
 *
 * @since 1.0.0
 *
 * @param string   $url        Redirect URL generated by ShortLinksPro.
 * @param stdClass $link       Link object.
 * @param string   $parameters Query parameters from the request.
 * @return string Redirect URL or placeholder URL for pixel redirects.
 */
add_filter( 'shortlinkspro_redirect_url', 'slp_advanced_bypass_empty_url_for_pixel', 10, 3 );
function slp_advanced_bypass_empty_url_for_pixel( $url, $link, $parameters ) {
    if ( isset( $link->redirect_type ) && $link->redirect_type === 'pixel' && empty( $url ) ) {
        return 'pixel-tracking-active';
    }
    return $url;
}

/**
 * Take control and render the pixel image for this redirect type.
 *
 * @since 1.0.0
 *
 * @param stdClass $link       Link object.
 * @param string   $parameters Query parameters from the request.
 * @param string   $url        Redirect URL generated by ShortLinksPro.
 */
add_action( 'shortlinkspro_process_redirect', 'slp_advanced_process_pixel_redirect', 10, 3 );
function slp_advanced_process_pixel_redirect( $link, $parameters, $url ) {
    if ( isset( $link->redirect_type ) && $link->redirect_type === 'pixel' ) {
        if ( ob_get_length() ) {
            ob_clean();
        }

        nocache_headers();
        header( 'Content-Type: image/gif' );
        header( 'Content-Length: 43' );
        header( 'Cache-Control: no-store, no-cache, must-revalidate, max-age=0' );
        header( 'Pragma: no-cache' );
        header( 'Expires: Wed, 11 Jan 1984 05:00:00 GMT' );

        echo base64_decode( 'R0lGODlhAQABAIABAP///wAAACwAAAAAAQABAAACAkQBADs=' );
        exit;
    }
}